# Generated by Django 3.2.4 on 2021-09-02 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_quesmodel2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuesModel2',
        ),
        migrations.AlterModelOptions(
            name='quesmodel',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='quesmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
